# Netlify配置文件

[build]
  publish = "dist"
  command = "npm run build"

# 重定向规则，基于vite.config.js中的代理配置
[[redirects]]
  from = "/api/*"
  to = "https://www.heimuer.tv/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ikun/*"
  to = "https://ikunzy.net/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/subo/*"
  to = "https://www.suboziyuan.net/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/huawei/*"
  to = "https://cjhwba.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/jisu/*"
  to = "https://www.jisuzy.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/360/*"
  to = "https://360zy5.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wolong/*"
  to = "https://wolongzyw.com/:splat"
  status = 200
  force = true

# SPA回退规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
